logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    host: 192.168.177.128 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: itcast
    password: 123321
    virtual-host: /
#开关配置
    #- publish-confirm-type：开启publisher-confirm，这里支持两种类型：
    #  -simple：同步等待confirm结果，直到超时
    publisher-confirm-type: correlated #-correlated：异步回调，定义ConfirmCallback，MQ返回结果时会回调这个ConfirmCallback
    #-publish-returns：开启publish-return功能，同样是基于callback机制，不过是定义ReturnCallback
    publisher-returns: true
    #-template.mandatory：定义消息路由失败时的策略。true，则调用ReturnCallback；false：则直接丢弃消息
    template:
      mandatory: true